# [START gcloud build gradle]
steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/user-service", "--build-arg=JAR_FILE=build/libs/user-service-1.0.1.jar", "."]
images: ["gcr.io/$PROJECT_ID/user-service"]
# [END gcloud build gradle]