server:
  port: 8080
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
spring: 
  cloud:    
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: presentation
        uri: lb://PresentationService
        predicates:
        - Path=/public/v1/**
      - id: jpademo
        uri: lb://JPADemo
        predicates:
        - Path=/private/v1/jpatest/**
  application:
    name: APIGateway
          